# Generated by Django 5.1.6 on 2025-02-19 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bloco', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Blocos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Empenho',
            fields=[
                ('numero_emp', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('valor_emp', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
            options={
                'verbose_name_plural': 'Empenhos',
            },
        ),
        migrations.CreateModel(
            name='Fiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fiscal', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Fiscais',
            },
        ),
        migrations.CreateModel(
            name='MesPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_pgto', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'MesPagamento',
            },
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Situacao',
            },
        ),
        migrations.CreateModel(
            name='EmpenhoUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_utilizado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('empenho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dserv.empenho')),
            ],
            options={
                'verbose_name_plural': 'EmpenhoUtilizado',
            },
        ),
        migrations.CreateModel(
            name='ManutencaoBloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_bloco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ambiente', models.CharField(max_length=400)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dserv.bloco')),
            ],
            options={
                'verbose_name_plural': 'ManutencaoBloco',
            },
        ),
        migrations.CreateModel(
            name='OrdemDeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('ano', models.IntegerField(default=2025)),
                ('processo', models.CharField(max_length=20)),
                ('prazo', models.IntegerField()),
                ('data_emissao', models.DateField()),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('blocos', models.ManyToManyField(through='dserv.ManutencaoBloco', to='dserv.bloco')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dserv.categoria')),
                ('empenhos', models.ManyToManyField(through='dserv.EmpenhoUtilizado', to='dserv.empenho')),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dserv.fiscal')),
                ('mespgto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dserv.mespagamento')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dserv.situacao')),
            ],
            options={
                'verbose_name_plural': 'OrdensDeServico',
            },
        ),
        migrations.AddField(
            model_name='manutencaobloco',
            name='ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dserv.ordemdeservico'),
        ),
        migrations.AddField(
            model_name='empenhoutilizado',
            name='ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dserv.ordemdeservico'),
        ),
        migrations.AddConstraint(
            model_name='ordemdeservico',
            constraint=models.UniqueConstraint(fields=('numero', 'ano'), name='numero_ano'),
        ),
    ]
