# Generated by Django 4.2.19 on 2025-03-07 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dserv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemdeservico',
            options={'permissions': [('cadastrar_ordem', 'Pode cadastrar nova ordem'), ('editar_ordem', 'Pode editar uma ordem cadastrada'), ('exportar_relatorio', 'Pode exportar relatório de pagamento')], 'verbose_name_plural': 'OrdensDeServico'},
        ),
        migrations.AlterField(
            model_name='empenhoutilizado',
            name='ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empenhos_utilizados', to='dserv.ordemdeservico'),
        ),
        migrations.AlterField(
            model_name='manutencaobloco',
            name='ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valor_por_bloco', to='dserv.ordemdeservico'),
        ),
    ]
