import os
import django
from datetime import datetime

# Configurações do Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'projeto_ufac.settings')
django.setup()

from dserv.models import OrdemDeServico, Fiscal, Categoria, Situacao, MesPagamento

# Dados das ordens de serviço
ordens = [
    {
        "numero": 101,
        "ano": 2025,
        "processo": "23107.003510/2025-11",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 10),
        "data_conclusao": None,
        "fiscal": "Edilberto Ferreira Jansen Júnior",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Manutenção em um cano com vazamento na máquina de lavar louça."
    },
    {
        "numero": 102,
        "ano": 2025,
        "processo": "23107.000582/2025-06",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 11),
        "data_conclusao": None,
        "fiscal": "Edilberto Ferreira Jansen Júnior",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Troca/reparo da caixa de descarga."
    },
    {
        "numero": 103,
        "ano": 2025,
        "processo": "23107.003517/2025-24",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 10),
        "data_conclusao": None,
        "fiscal": "Edilberto Ferreira Jansen Júnior",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Substituição e instalação de tambores de fechadura."
    },
    {
        "numero": 104,
        "ano": 2025,
        "processo": "23107.004172/2025-26",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 11),
        "data_conclusao": None,
        "fiscal": "Edilberto Ferreira Jansen Júnior",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Manutenção na porta."
    },
    {
        "numero": 105,
        "ano": 2025,
        "processo": "23107.004342/2025-72",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 11),
        "data_conclusao": None,
        "fiscal": "Emerson Henrique Costa de Araújo",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Substituição da fechadura."
    },
    {
        "numero": 106,
        "ano": 2025,
        "processo": "23107.022409/2025-70",
        "prazo": 30,
        "data_emissao": datetime(2025, 2, 12),
        "data_conclusao": None,
        "fiscal": "Lisângela Pazinatto",
        "categoria": "ORDINARIA",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Manutenção do forro em madeira com pintura branca, localizado nas circulações da edificação e manutenção do forro em madeira, com acabamento em verniz."
    },
    {
        "numero": 107,
        "ano": 2025,
        "processo": "23107.018398/2025-23",
        "prazo": 30,
        "data_emissao": datetime(2025, 2, 12),
        "data_conclusao": None,
        "fiscal": "Lisângela Pazinatto",
        "categoria": "ORDINARIA",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Fechamento com microtela e peças em madeira das áreas abertas entre o forro e a cobertura em todo o perímetro dos Blocos."
    },
    {
        "numero": 108,
        "ano": 2025,
        "processo": "23107.003002/2025-24",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 11),
        "data_conclusao": None,
        "fiscal": "Edilberto Ferreira Jansen Júnior",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Manutenção do forro."
    },
    {
        "numero": 110,
        "ano": 2025,
        "processo": "23107.004908/2025-66",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 12),
        "data_conclusao": None,
        "fiscal": "Emerson Henrique Costa de Araújo",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Torneiras que não fecham e estão desperdiçando água."
    },
    {
        "numero": 111,
        "ano": 2025,
        "processo": "23107.004950/2025-87",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 12),
        "data_conclusao": None,
        "fiscal": "Emerson Henrique Costa de Araújo",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Manutenção da porta de vidro."
    },
    {
        "numero": 113,
        "ano": 2025,
        "processo": "23107.005036/2025-53",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 12),
        "data_conclusao": None,
        "fiscal": "Emerson Henrique Costa de Araújo",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Entupimento nos dois vasos sanitários."
    },
    {
        "numero": 115,
        "ano": 2025,
        "processo": "23107.004400/2025-68",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 12),
        "data_conclusao": None,
        "fiscal": "Emerson Henrique Costa de Araújo",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Troca de 1 assento."
    },
    {
        "numero": 116,
        "ano": 2025,
        "processo": "23107.028068/2024-46",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 13),
        "data_conclusao": None,
        "fiscal": "Emerson Henrique Costa de Araújo",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Manutenção do forro-laje."
    },
    {
        "numero": 117,
        "ano": 2025,
        "processo": "23107.005102/2025-95",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 13),
        "data_conclusao": None,
        "fiscal": "Emerson Henrique Costa de Araújo",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Manutenção na porta de entrada."
    },
    {
        "numero": 118,
        "ano": 2025,
        "processo": "23107.004555/2025-02",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 13),
        "data_conclusao": None,
        "fiscal": "Emerson Henrique Costa de Araújo",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Manutenção em torneira."
    },
    {
        "numero": 119,
        "ano": 2025,
        "processo": "23107.004316/2025-44",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 13),
        "data_conclusao": None,
        "fiscal": "Edilberto Ferreira Jansen Júnior",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Telhado e troca de uma torneira."
    },
    {
        "numero": 120,
        "ano": 2025,
        "processo": "23107.005078/2025-94",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 13),
        "data_conclusao": None,
        "fiscal": "Edilberto Ferreira Jansen Júnior",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Manutenção dos banheiros."
    },
    {
        "numero": 121,
        "ano": 2025,
        "processo": "23107.005246/2025-41",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 13),
        "data_conclusao": None,
        "fiscal": "Emerson Henrique Costa de Araújo",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Goteiras."
    },
    {
        "numero": 122,
        "ano": 2025,
        "processo": "23107.005248/2025-31",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 13),
        "data_conclusao": None,
        "fiscal": "Emerson Henrique Costa de Araújo",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Goteiras."
    },
    {
        "numero": 123,
        "ano": 2025,
        "processo": "23107.005288/2025-82",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 13),
        "data_conclusao": None,
        "fiscal": "Emerson Henrique Costa de Araújo",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Infiltração de água vindo do forro."
    },
    {
        "numero": 125,
        "ano": 2025,
        "processo": "23107.005181/2025-34",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 14),
        "data_conclusao": None,
        "fiscal": "Edilberto Ferreira Jansen Júnior",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Manutenção na porta de vidro do hall."
    },
    {
        "numero": 126,
        "ano": 2025,
        "processo": "23107.033064/2024-80",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 14),
        "data_conclusao": None,
        "fiscal": "Edilberto Ferreira Jansen Júnior",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Manutenção de piso."
    },
    {
        "numero": 127,
        "ano": 2025,
        "processo": "23107.005339/2025-76",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 14),
        "data_conclusao": None,
        "fiscal": "Emerson Henrique Costa de Araújo",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Instalação de uma nova porta."
    },
    {
        "numero": 128,
        "ano": 2025,
        "processo": "23107.005350/2025-36",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 14),
        "data_conclusao": None,
        "fiscal": "Emerson Henrique Costa de Araújo",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Vazamento no banheiro."
    },
    {
        "numero": 129,
        "ano": 2025,
        "processo": "23107.005379/2025-18",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 14),
        "data_conclusao": None,
        "fiscal": "Emerson Henrique Costa de Araújo",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Vasos sanitários entupidos e sistemas de descarga com defeito."
    },
    {
        "numero": 130,
        "ano": 2025,
        "processo": "23107.005354/2025-14",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 17),
        "data_conclusao": None,
        "fiscal": "Emerson Henrique Costa de Araújo",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Troca das fechaduras e a substituição das placas de identificação."
    },
    {
        "numero": 131,
        "ano": 2025,
        "processo": "23107.031917/2024-49",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 14),
        "data_conclusao": None,
        "fiscal": "Edilberto Ferreira Jansen Júnior",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Instalação de suportes para papel higiênico e saboneteira, manutenção em descarga."
    },
    {
        "numero": 132,
        "ano": 2025,
        "processo": "23107.004369/2025-65",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 15),
        "data_conclusao": None,
        "fiscal": "Edilberto Ferreira Jansen Júnior",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Manutenção nas caixas onde passam os drenos dos aparelhos de ar condicionado."
    },
    {
        "numero": 133,
        "ano": 2025,
        "processo": "23107.032276/2024-40",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 18),
        "data_conclusao": None,
        "fiscal": "Edilberto Ferreira Jansen Júnior",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Manutenção no piso cerâmico."
    },
    {
        "numero": 134,
        "ano": 2025,
        "processo": "23107.005546/2025-21",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 17),
        "data_conclusao": None,
        "fiscal": "Edilberto Ferreira Jansen Júnior",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Instalação de hidrômetro."
    },
    {
        "numero": 135,
        "ano": 2025,
        "processo": "23107.005557/2025-19",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 17),
        "data_conclusao": None,
        "fiscal": "Edilberto Ferreira Jansen Júnior",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Manutenção da janela que saiu do trilho."
    },
    {
        "numero": 136,
        "ano": 2025,
        "processo": "23107.016403/2024-63",
        "prazo": 30,
        "data_emissao": datetime(2025, 2, 18),
        "data_conclusao": None,
        "fiscal": "Lisângela Pazinatto",
        "categoria": "ORDINARIA",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Manutenção de piso na área de carga e descarga, piso dos degrais, nivelamento de patamar antes da escada e instalação de grelha metálica na porta de acesso."
    },
    {
        "numero": 137,
        "ano": 2025,
        "processo": "23107.005418/2025-87",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 18),
        "data_conclusao": None,
        "fiscal": "Edilberto Ferreira Jansen Júnior",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Árvore caiu e danificou parte da estrutura."
    },
    {
        "numero": 138,
        "ano": 2025,
        "processo": "23107.005678/2025-52",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 18),
        "data_conclusao": None,
        "fiscal": "Emerson Henrique Costa de Araújo",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Manutenção na telha da passarela ao lado do Anfiteatro."
    },
    {
        "numero": 139,
        "ano": 2025,
        "processo": "23107.005683/2025-65",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 18),
        "data_conclusao": None,
        "fiscal": "Emerson Henrique Costa de Araújo",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Vasos sanitários apresentam vazamento."
    },
    {
        "numero": 140,
        "ano": 2025,
        "processo": "23107.005686/2025-07",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 18),
        "data_conclusao": None,
        "fiscal": "Edilberto Ferreira Jansen Júnior",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Manutenção na bomba da cisterna grande que abastece o Restaurante Universitário."
    },
    {
        "numero": 141,
        "ano": 2025,
        "processo": "23107.005567/2025-46",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 18),
        "data_conclusao": None,
        "fiscal": "Emerson Henrique Costa de Araújo",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Manutenção da rede de esgoto/ralos do banheiros."
    },
    {
        "numero": 142,
        "ano": 2025,
        "processo": "23107.005685/2025-54",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 18),
        "data_conclusao": None,
        "fiscal": "Emerson Henrique Costa de Araújo",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Manutenção da bomba d'água."
    },
    {
        "numero": 144,
        "ano": 2025,
        "processo": "23107.001183/2025-54",
        "prazo": 30,
        "data_emissao": datetime(2025, 2, 18),
        "data_conclusao": None,
        "fiscal": "Lisângela Pazinatto",
        "categoria": "ORDINARIA",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Película protetiva fumê."
    },
    {
        "numero": 145,
        "ano": 2025,
        "processo": "23107.005587/2025-17",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 18),
        "data_conclusao": None,
        "fiscal": "Emerson Henrique Costa de Araújo",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Fechadura."
    },
    {
        "numero": 146,
        "ano": 2025,
        "processo": "23107.017071/2023-53",
        "prazo": 30,
        "data_emissao": datetime(2025, 2, 18),
        "data_conclusao": None,
        "fiscal": "Emerson Henrique Costa de Araújo",
        "categoria": "ORDINARIA",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Manutenção em divisórias."
    },
    {
        "numero": 147,
        "ano": 2025,
        "processo": "23107.005464/2025-86",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 18),
        "data_conclusao": None,
        "fiscal": "Emerson Henrique Costa de Araújo",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Manutenção no acionador de descarga."
    },
    {
        "numero": 148,
        "ano": 2025,
        "processo": "23107.031062/2023-75",
        "prazo": 30,
        "data_emissao": datetime(2025, 2, 18),
        "data_conclusao": None,
        "fiscal": "Edilberto Ferreira Jansen Júnior",
        "categoria": "ORDINARIA",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Fechamento de vão e abertura de porta para o corredor."
    },
    {
        "numero": 149,
        "ano": 2025,
        "processo": "23107.005408/2025-41",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 18),
        "data_conclusao": None,
        "fiscal": "Emerson Henrique Costa de Araújo",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Manutenção na fechadura."
    },
    {
        "numero": 150,
        "ano": 2025,
        "processo": "23107.002113/2025-13",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 18),
        "data_conclusao": None,
        "fiscal": "Emerson Henrique Costa de Araújo",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Manutenção da bomba d'água."
    },
    {
        "numero": 151,
        "ano": 2025,
        "processo": "23107.005205/2025-55",
        "prazo": 1,
        "data_emissao": datetime(2025, 2, 18),
        "data_conclusao": None,
        "fiscal": "Emerson Henrique Costa de Araújo",
        "categoria": "EMERGENCIAL",
        "situacao": "EM ANDAMENTO",
        "mespgto": "fevereiro/2025",
        "descricao": "Fechadura."
    },
]

# Inserção dos dados no banco de dados
for ordem in ordens:
    fiscal, _ = Fiscal.objects.get_or_create(nome_fiscal=ordem['fiscal'])
    categoria, _ = Categoria.objects.get_or_create(categoria=ordem['categoria'])
    situacao, _ = Situacao.objects.get_or_create(situacao=ordem['situacao'])
    mespgto, _ = MesPagamento.objects.get_or_create(mes_pgto=ordem['mespgto'])
    
    OrdemDeServico.objects.create(
        numero=ordem['numero'],
        ano=ordem['ano'],
        processo=ordem['processo'],
        prazo=ordem['prazo'],
        data_emissao=ordem['data_emissao'],
        data_conclusao=ordem['data_conclusao'],
        fiscal=fiscal,
        categoria=categoria,
        situacao=situacao,
        mespgto=mespgto,
        descricao=ordem['descricao']
    )

print("Dados inseridos com sucesso!")
