import os
import django
from datetime import datetime

# Configurações do Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'projeto_ufac.settings')
django.setup()

from dserv.models import OrdemDeServico, Bloco, ManutencaoBloco

# Dados das manutenções por bloco
manutencoes = [
    {"num_os": 42, "ano_os": 2025, "bloco": "Fernando Melo de Andrade", "valor_manutencao": 0, "sala": "Rede Cedes"},
    {"num_os": 43, "ano_os": 2025, "bloco": "Rubem Ludwig", "valor_manutencao": 0, "sala": "Corredor, CAQui e Lab. de Físico-química"},
    {"num_os": 44, "ano_os": 2025, "bloco": "Núcleo de Sena Madureira", "valor_manutencao": 0, "sala": "Apartamentos/banheiro"},
    {"num_os": 45, "ano_os": 2025, "bloco": "Euclydes de Oliveira Figueiredo", "valor_manutencao": 0, "sala": "Banheiros"},
    {"num_os": 45, "ano_os": 2025, "bloco": "Djalma Batista", "valor_manutencao": 0, "sala": "Banheiros"},
    {"num_os": 45, "ano_os": 2025, "bloco": "Áulio Gélio Alves de Souza", "valor_manutencao": 0, "sala": "Banheiros"},
    {"num_os": 45, "ano_os": 2025, "bloco": "Zaqueu M. de Almeida", "valor_manutencao": 0, "sala": "Banheiros"},
    {"num_os": 45, "ano_os": 2025, "bloco": "Augusto César de Sá da Rocha Maia", "valor_manutencao": 0, "sala": "Banheiros"},
    {"num_os": 45, "ano_os": 2025, "bloco": "João Mendonça Furtado", "valor_manutencao": 0, "sala": "Banheiros"},
    {"num_os": 46, "ano_os": 2025, "bloco": "Colégio Aplicação (DETRAN)", "valor_manutencao": 0, "sala": "Brinquedoteca"},
    {"num_os": 47, "ano_os": 2025, "bloco": "Ruy Alberto da Costa Lins", "valor_manutencao": 0, "sala": "Salão de estudos"},
    {"num_os": 48, "ano_os": 2025, "bloco": "Ruy Alberto da Costa Lins", "valor_manutencao": 31.59, "sala": "Banheiro masculino do piso superior"},
    {"num_os": 49, "ano_os": 2025, "bloco": "Ruy Alberto da Costa Lins", "valor_manutencao": 145.1, "sala": "Banheiros masculino e feminino"},
    {"num_os": 50, "ano_os": 2025, "bloco": "Laércio Vanderley da Nóbrega", "valor_manutencao": 0, "sala": "Indução"},
    {"num_os": 51, "ano_os": 2025, "bloco": "Felix Bestene Neto", "valor_manutencao": 0, "sala": "Banheiro masculino"},
    {"num_os": 52, "ano_os": 2025, "bloco": "Enoque Nunes de Freitas", "valor_manutencao": 0, "sala": "Banheiros"},
    {"num_os": 53, "ano_os": 2025, "bloco": "Esther de Figueiredo Ferraz", "valor_manutencao": 0, "sala": "Propeg/banheiro"},
    {"num_os": 54, "ano_os": 2025, "bloco": "Garibalde Brasil", "valor_manutencao": 0, "sala": "Anfiteatro"},
    {"num_os": 56, "ano_os": 2025, "bloco": "Laércio Vanderley da Nóbrega", "valor_manutencao": 10.69, "sala": "Laboratório de Doenças Infecciosas dos Animais"},
    {"num_os": 57, "ano_os": 2025, "bloco": "Edilberto Parigot", "valor_manutencao": 0, "sala": "Banheiro"},
    {"num_os": 58, "ano_os": 2025, "bloco": "Nely Catunda da Cruz", "valor_manutencao": 0, "sala": "Sala 05"},
    {"num_os": 63, "ano_os": 2025, "bloco": "Departamento de Educação Física", "valor_manutencao": 0, "sala": "Banheiros"},
    {"num_os": 64, "ano_os": 2025, "bloco": "Bloco de Pós Graduação", "valor_manutencao": 0, "sala": "Banheiros"},
    {"num_os": 66, "ano_os": 2025, "bloco": "Enoque Nunes de Freitas", "valor_manutencao": 0, "sala": "Banheiro"},
    {"num_os": 67, "ano_os": 2025, "bloco": "Fernando Melo de Andrade", "valor_manutencao": 0, "sala": "Laboratório Multidisciplinar de Ciências do Esporte"},
    {"num_os": 69, "ano_os": 2025, "bloco": "Walter Félix de Souza II", "valor_manutencao": 0, "sala": "Centro Acadêmico Pedro Martinello"},
    {"num_os": 70, "ano_os": 2025, "bloco": "Parque Zoobotânico - Bloco Administrativo", "valor_manutencao": 0, "sala": "Externo"},
    {"num_os": 71, "ano_os": 2025, "bloco": "Jorge Kalume", "valor_manutencao": 0, "sala": "Banheiros"},
    {"num_os": 71, "ano_os": 2025, "bloco": "Mário David Andreazza", "valor_manutencao": 0, "sala": "Banheiros"},
    {"num_os": 79, "ano_os": 2025, "bloco": "Jersey Nazareno de B. Nunes", "valor_manutencao": 91173.37, "sala": "Sala dos Estudantes e salas 2, 3, 4 e 5; Cobertura; Circulação Geral; Laboratório de Informática e de Didática de Matemática"},
    {"num_os": 83, "ano_os": 2025, "bloco": "Enoque Nunes de Freitas", "valor_manutencao": 0, "sala": "Banheiro do Vestiário Feminino"},
    {"num_os": 84, "ano_os": 2025, "bloco": "Francisca Corina de A. F.", "valor_manutencao": 0, "sala": "PASSARELA"},
    {"num_os": 85, "ano_os": 2025, "bloco": "Multidisciplinar", "valor_manutencao": 0, "sala": "Banheiro Feminino"},
    {"num_os": 86, "ano_os": 2025, "bloco": "Antigo Medicina", "valor_manutencao": 831.87, "sala": "SALA DO DIRETÓRIO ACADÊMICO DE FÍSICA"},
    {"num_os": 87, "ano_os": 2025, "bloco": "Mário Alves Ribeiro (UEPMV)", "valor_manutencao": 0, "sala": "Banheiros Femininos"},
    {"num_os": 89, "ano_os": 2025, "bloco": "Bloco novo da Física (Antigo CAP)", "valor_manutencao": 0, "sala": "Banheiro"},
    {"num_os": 90, "ano_os": 2025, "bloco": "Fernando Melo de Andrade", "valor_manutencao": 0, "sala": "Salas 01 e 02"},
    {"num_os": 91, "ano_os": 2025, "bloco": "Serviço-Escola de Psicologia", "valor_manutencao": 0, "sala": "Banheiro feminino"},
    {"num_os": 92, "ano_os": 2025, "bloco": "Granja", "valor_manutencao": 0, "sala": "LABORATÓRIO DE FITOTECNIA"},
    {"num_os": 92, "ano_os": 2025, "bloco": "Bloco do Laboratório de Fitotecnia", "valor_manutencao": 0, "sala": "Granja e Laboratório de Fitotecnia"},
    {"num_os": 93, "ano_os": 2025, "bloco": "Parque Zoobotânico - Bloco Administrativo", "valor_manutencao": 0, "sala": "Prédio do Arboreto"},
    {"num_os": 94, "ano_os": 2025, "bloco": "Bloco do Arquivo Central/NURCA", "valor_manutencao": 65.88, "sala": "Banheiro Masculino"},
    {"num_os": 95, "ano_os": 2025, "bloco": "Edilberto Parigot", "valor_manutencao": 0, "sala": "Banheiro masculino"},
    {"num_os": 96, "ano_os": 2025, "bloco": "Teatro Universitário", "valor_manutencao": 15815.61, "sala": "Forro"},
    {"num_os": 98, "ano_os": 2025, "bloco": "Mário David Andreazza", "valor_manutencao": 1650.63, "sala": "Sala do Prof. Dr. Jose Cabral Mendes"},
    {"num_os": 99, "ano_os": 2025, "bloco": "Centro de Convivência", "valor_manutencao": 0, "sala": "Porta de vidro do SEBRAE LAB."},
    {"num_os": 100, "ano_os": 2025, "bloco": "Áulio Gélio Alves de Souza", "valor_manutencao": 0, "sala": "Laboratório de mecanização"},
    {"num_os": 101, "ano_os": 2025, "bloco": "Enoque Nunes de Freitas", "valor_manutencao": 0, "sala": "Restaurante Universitário"},
    {"num_os": 102, "ano_os": 2025, "bloco": "Transportes e Garagem", "valor_manutencao": 0, "sala": "Banheiro"},
    {"num_os": 103, "ano_os": 2025, "bloco": "Colégio Aplicação (DETRAN)", "valor_manutencao": 0, "sala": "Porta da Cozinha"},
    {"num_os": 104, "ano_os": 2025, "bloco": "Joaquim Falcão Macêdo", "valor_manutencao": 0, "sala": "Porta da coordenação do curso de ciências econômicas."},
    {"num_os": 105, "ano_os": 2025, "bloco": "Centro de Convenções", "valor_manutencao": 0, "sala": "SALA 02"},
    {"num_os": 106, "ano_os": 2025, "bloco": "Joaquim Falcão Macêdo", "valor_manutencao": 22402.64, "sala": "Forro da circulação da edificação."},
    {"num_os": 107, "ano_os": 2025, "bloco": "Mário David Andreazza", "valor_manutencao": 41192.23, "sala": "Forro e cobertura"},
    {"num_os": 107, "ano_os": 2025, "bloco": "Joaquim Falcão Macêdo", "valor_manutencao": 41192.23, "sala": "Forro"},
    {"num_os": 108, "ano_os": 2025, "bloco": "Walter Félix de Souza II", "valor_manutencao": 0, "sala": "Acadêmico Pedro Martinello"},
    {"num_os": 110, "ano_os": 2025, "bloco": "Multidisciplinar", "valor_manutencao": 0, "sala": "Banheiro feminino - piso superior"},
    {"num_os": 111, "ano_os": 2025, "bloco": "Elias Mansour Simão Filho", "valor_manutencao": 0, "sala": "Diretoria de Obras e Projetos 1° piso"},
    {"num_os": 113, "ano_os": 2025, "bloco": "Enoque Nunes de Freitas", "valor_manutencao": 0, "sala": "Banheiro feminino (funcionários) do RU"},
    {"num_os": 115, "ano_os": 2025, "bloco": "Antigo Medicina", "valor_manutencao": 0, "sala": "Banheiro feminino (andar superior)."},
    {"num_os": 116, "ano_os": 2025, "bloco": "Laércio Vanderley da Nóbrega", "valor_manutencao": 0, "sala": "Clínica Médica Veterinária"},
    {"num_os": 117, "ano_os": 2025, "bloco": "Fernando Melo de Andrade", "valor_manutencao": 0, "sala": "Porta do Biotério"},
    {"num_os": 118, "ano_os": 2025, "bloco": "Bloco Multifuncional", "valor_manutencao": 0, "sala": "Copa"},
    {"num_os": 119, "ano_os": 2025, "bloco": "Mário David Andreazza", "valor_manutencao": 0, "sala": "Bloco de História (sala 01) e banheiro masculino"},
    {"num_os": 120, "ano_os": 2025, "bloco": "Centro de Convenções", "valor_manutencao": 0, "sala": "Banheiros"},
    {"num_os": 121, "ano_os": 2025, "bloco": "Enoque Nunes de Freitas", "valor_manutencao": 0, "sala": "Área de produção de alimentos"},
    {"num_os": 122, "ano_os": 2025, "bloco": "Ruy Alberto da Costa Lins", "valor_manutencao": 0, "sala": "Acervo da biblioteca central e na rampa de acesso ao anexo."},
    {"num_os": 123, "ano_os": 2025, "bloco": "Mário David Andreazza", "valor_manutencao": 0, "sala": "Sala de docente [localizada no segundo piso]."},
    {"num_os": 125, "ano_os": 2025, "bloco": "Mário Alves Ribeiro (UEPMV)", "valor_manutencao": 0, "sala": "Hall da UEPMV."},
    {"num_os": 126, "ano_os": 2025, "bloco": "Walter Félix de Souza II", "valor_manutencao": 0, "sala": "Sala de aula 02"},
    {"num_os": 127, "ano_os": 2025, "bloco": "Colégio Aplicação (DETRAN)", "valor_manutencao": 0, "sala": "Banheiro masculino do nível 2"},
    {"num_os": 128, "ano_os": 2025, "bloco": "Colégio Aplicação (DETRAN)", "valor_manutencao": 0, "sala": "Banheiro feminino do nível 2"},
    {"num_os": 129, "ano_os": 2025, "bloco": "Colégio Aplicação (DETRAN)", "valor_manutencao": 0, "sala": "Banheiro masculino"},
    {"num_os": 130, "ano_os": 2025, "bloco": "Elias Mansour Simão Filho", "valor_manutencao": 0, "sala": "Banheiros"},
    {"num_os": 131, "ano_os": 2025, "bloco": "Geraldo Gurgel de Mesquita", "valor_manutencao": 0, "sala": "Banheiro Masculino e feminino."},
    {"num_os": 132, "ano_os": 2025, "bloco": "Bloco novo da pós graduação", "valor_manutencao": 0, "sala": "Salas da Pró-reitoria de Administração."},
    {"num_os": 133, "ano_os": 2025, "bloco": "Ruy Alberto da Costa Lins", "valor_manutencao": 0, "sala": "PISO EXTERNO - TÉRREO, PRÓXIMO AOS SANITÁRIOS"},
    {"num_os": 134, "ano_os": 2025, "bloco": "Horta", "valor_manutencao": 0, "sala": "Cisterna do Elevado"},
    {"num_os": 135, "ano_os": 2025, "bloco": "Nely Catunda da Cruz", "valor_manutencao": 0, "sala": "SALA 4"},
    {"num_os": 136, "ano_os": 2025, "bloco": "Enoque Nunes de Freitas", "valor_manutencao": 13351.75, "sala": "Várias partes do Restaurante Universitário."},
    {"num_os": 137, "ano_os": 2025, "bloco": "Reserva florestal Humaitá", "valor_manutencao": 0, "sala": "alojamento da reserva"},
    {"num_os": 138, "ano_os": 2025, "bloco": "Garibalde Brasil", "valor_manutencao": 0, "sala": "Passarela"},
    {"num_os": 139, "ano_os": 2025, "bloco": "Rubem Ludwig", "valor_manutencao": 0, "sala": "Banheiro feminino."},
    {"num_os": 140, "ano_os": 2025, "bloco": "Enoque Nunes de Freitas", "valor_manutencao": 0, "sala": "Bomba d'água do RU"},
    {"num_os": 141, "ano_os": 2025, "bloco": "Joaquim Pessoa Lopes Igrejas", "valor_manutencao": 0, "sala": "Banheiros"},
    {"num_os": 142, "ano_os": 2025, "bloco": "Mário Alves Ribeiro (UEPMV)", "valor_manutencao": 0, "sala": "ÁREA EXTERNA"},
    {"num_os": 144, "ano_os": 2025, "bloco": "Elias Mansour Simão Filho", "valor_manutencao": 893.06, "sala": "Sala depósito"},
    {"num_os": 145, "ano_os": 2025, "bloco": "Ruy Alberto da Costa Lins", "valor_manutencao": 0, "sala": "Porta do salão de estudo"},
    {"num_os": 146, "ano_os": 2025, "bloco": "Ruy Alberto da Costa Lins", "valor_manutencao": 243.51, "sala": "Entrada de acesso e próximo ao elevador de acessibilidade."},
    {"num_os": 147, "ano_os": 2025, "bloco": "Áulio Gélio Alves de Souza", "valor_manutencao": 0, "sala": "Banheiro Masculino"},
    {"num_os": 148, "ano_os": 2025, "bloco": "Áulio Gélio Alves de Souza", "valor_manutencao": 2437.39, "sala": "SALA DO PROF DIODOMIRO"},
    {"num_os": 149, "ano_os": 2025, "bloco": "Francisco Cavalcanti Mangabeira", "valor_manutencao": 0, "sala": "sala 20 (sala da coordenação)"},
    {"num_os": 150, "ano_os": 2025, "bloco": "Joaquim Pessoa Lopes Igrejas", "valor_manutencao": 0, "sala": "Utal"},
    {"num_os": 151, "ano_os": 2025, "bloco": "Lucia Kiyoko Ozari Yuyana", "valor_manutencao": 0, "sala": "sala 03"},
    {"num_os": 152, "ano_os": 2025, "bloco": "Francisco Cavalcanti Mangabeira", "valor_manutencao": 0, "sala": "Banheiros"},
    {"num_os": 153, "ano_os": 2025, "bloco": "Enoque Nunes de Freitas", "valor_manutencao": 0, "sala": "Porta do refeitório do RU"},
    {"num_os": 155, "ano_os": 2025, "bloco": "Teatro Universitário", "valor_manutencao": 0, "sala": "sala de máquinas do ar-condicionado central"},
    {"num_os": 156, "ano_os": 2025, "bloco": "Bloco do Arquivo Central/NURCA", "valor_manutencao": 0, "sala": "SAGUÃO DO PRÉDIO"},
    {"num_os": 157, "ano_os": 2025, "bloco": "Francisco Cavalcanti Mangabeira", "valor_manutencao": 0, "sala": "corredores do térreo e 1º piso"},
    {"num_os": 159, "ano_os": 2025, "bloco": "Garibalde Brasil", "valor_manutencao": 3427.59, "sala": "circulações da plateia"},
    {"num_os": 160, "ano_os": 2025, "bloco": "Esther de Figueiredo Ferraz", "valor_manutencao": 4024.74, "sala": "rampa de acesso do estacionamento ao Anfiteatro Garibaldi Brasil"},
    {"num_os": 161, "ano_os": 2025, "bloco": "Áulio Gélio Alves de Souza", "valor_manutencao": 0, "sala": "Sala 04"},
    {"num_os": 162, "ano_os": 2025, "bloco": "Felix Bestene Neto", "valor_manutencao": 0, "sala": "Banheiro masculino do Lab. de anatomia humana"},
    {"num_os": 164, "ano_os": 2025, "bloco": "Elda Moreira de Oliveira", "valor_manutencao": 0, "sala": "CCBN/MUSEU UNIVERSITARIO"},
    {"num_os": 165, "ano_os": 2025, "bloco": "Edilberto Parigot", "valor_manutencao": 0, "sala": "banheiro feminino do NAI"},
    {"num_os": 168, "ano_os": 2025, "bloco": "Edilberto Parigot", "valor_manutencao": 0, "sala": "banheiro masculino"},
    {"num_os": 169, "ano_os": 2025, "bloco": "Francisco Augusto Vieira Nunes", "valor_manutencao": 0, "sala": "banheiro do bloco CCSD"},
    {"num_os": 170, "ano_os": 2025, "bloco": "Parque Zoobotânico - Bloco Administrativo", "valor_manutencao": 0, "sala": "cerca de arame."},
    {"num_os": 171, "ano_os": 2025, "bloco": "Elda Moreira de Oliveira", "valor_manutencao": 0, "sala": "Laboratório de Anatomia Animal"},
    {"num_os": 172, "ano_os": 2025, "bloco": "Rubem Ludwig", "valor_manutencao": 0, "sala": "todo bloco."},
    {"num_os": 173, "ano_os": 2025, "bloco": "Zaqueu M. de Almeida", "valor_manutencao": 0, "sala": "LAB. DE SEMENTES E FITOPATOLOGIA"},
    {"num_os": 174, "ano_os": 2025, "bloco": "Edilberto Parigot", "valor_manutencao": 0, "sala": "banheiro masculino localizado do Térreo"},
    {"num_os": 175, "ano_os": 2025, "bloco": "Joaquim Pessoa Lopes Igrejas", "valor_manutencao": 0, "sala": "Bloco da Estação de Geofísica Aplicada da UFAC, próximo à UTAL, 1º piso. Sala da Prodgep."},
    {"num_os": 176, "ano_os": 2025, "bloco": "Djalma Batista", "valor_manutencao": 0, "sala": "Laboratório de fertilidade do solo"},
    {"num_os": 177, "ano_os": 2025, "bloco": "Ruy Alberto da Costa Lins", "valor_manutencao": 0, "sala": "RAMPA DE ACESSO AO ANEXO"},
    {"num_os": 178, "ano_os": 2025, "bloco": "Felix Bestene Neto", "valor_manutencao": 0, "sala": "banheiro feminino"},
    {"num_os": 180, "ano_os": 2025, "bloco": "Enoque Nunes de Freitas", "valor_manutencao": 0, "sala": "Entrada do RU"},
    {"num_os": 181, "ano_os": 2025, "bloco": "Edilberto Parigot", "valor_manutencao": 0, "sala": "banheiro masculino do Curso de Bacharelado em Psicologia"},
    {"num_os": 182, "ano_os": 2025, "bloco": "Enoque Nunes de Freitas", "valor_manutencao": 0, "sala": "vestiário masculino do RU"},
    {"num_os": 183, "ano_os": 2025, "bloco": "JOÃO LUÍS CONSTANTE DE MORAES (PROXIMO CCBN)", "valor_manutencao": 0, "sala": "LABORATÓRIO LABEV. (MARCOS SILVEIRA)"},
    {"num_os": 184, "ano_os": 2025, "bloco": "Antigo Medicina", "valor_manutencao": 0, "sala": "Laje do corredor do Bloco Novo de física."},
    {"num_os": 185, "ano_os": 2025, "bloco": "Parque Zoobotânico - Bloco Administrativo", "valor_manutencao": 0, "sala": "Banheiro do Setem"},
    {"num_os": 187, "ano_os": 2025, "bloco": "Edilberto Parigot", "valor_manutencao": 0, "sala": "Curso de Psicologia (sala 06)"},
    {"num_os": 189, "ano_os": 2025, "bloco": "Serviço-Escola de Psicologia", "valor_manutencao": 2184.27, "sala": "corredor"},
]

]

# Inserção dos dados no banco de dados
for manutencao in manutencoes:
    ordem = OrdemDeServico.objects.get(numero=manutencao['num_os'], ano=manutencao['ano_os'])
    bloco, _ = Bloco.objects.get_or_create(nome_bloco=manutencao['bloco'])
    
    ManutencaoBloco.objects.create(
        ordem=ordem,
        bloco=bloco,
        valor_bloco=manutencao['valor_manutencao'],
        ambiente=manutencao['sala']
    )

print("Dados inseridos com sucesso!")
